### ISSUE TITLE
Not a bug; How do we install this into the Remarkable ?

### ISSUE THREAD

**Issue by rdc02271** [sandsmark/recrossable#1]
Hello,

Where can I find the instructions to install this into the Remarkable?

I am trying to figure out how to do some real time handwritten text recognition in the Remarkable to then (somehow) fill out a form...

So I would like to test this app of yours.

Thank you,
Jorge

**Comment by Ameb** [comment]
Those instructions should apply: https://dragly.org/2017/12/01/developing-for-the-remarkable/
Also https://remarkablewiki.com/devel/qt_creator

You need a linux system and the toolchain provided by reMarkable.

**Comment by sandsmark** [comment]
sorry for the late reply, but didn't see this, but Ameb is correct.

set up the toolchain, run `qmake && make && make deploy` (iirc qmake sets up a deploy target, otherwise just copy over the files manually).
