### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Eeems** [sandsmark/recrossable#2]
What license is this under?

**Comment by sandsmark** [comment]
it inherits the license from cwc, so gplv2 or later

**Comment by Eeems** [comment]
Could you add a LICENSE to the repository so it's clear to everybody? Especially since you have this line in the cwc file headers:
> You should have received a copy of the GNU General Public License along with this program;

**Comment by sandsmark** [comment]
way ahead of you (approximately 2 minutes)
