### ISSUE TITLE
Pen input on Qt 5.11

### ISSUE THREAD

**Issue by matteodelabre** [sandsmark/recrossable#3]
Even though I’m building with Qt 5.11, the pen input does not seem to register unless I force the use of [this workaround](https://github.com/sandsmark/recrossable/blob/6c2c8b1d3d2ec3f3978078f941b09d8cc525f4c6/main.cpp#L22) which, according to the code, is meant for Qt 5.6.

**Comment by sandsmark** [comment]
I think the check was there because `Qt::AA_SynthesizeMouseForUnhandledTabletEvents` didn't exist in Qt before 5.7. But I'll just drop the check, the hack doesn't really hurt anything (except it's more code).
