### ISSUE TITLE
No clear way to undo/erase entries

### ISSUE THREAD

**Issue by Snowflake6** [sandsmark/recrossable#5]
An Eraser or even an Undo button would be useful.

**Comment by sandsmark** [comment]
you can "clear" it by scribbling/"scratching" over the text, or just cover what is written (it checks if you have tried covering more than 25% of the cell), then it clears the contents.

I wanted to keep the UI minimal, but it might not be very obvious how it works.

**Comment by Snowflake6** [comment]
I just found this by accident last night.  :)  I tried scribbling before posting the issue, but I guess I didn't scribble enough.  Then last night I wrote too much in a cell and it cleared!  So I spent some time figuring out how best to "scribble" to get rid of a letter.  Knowing how it works it now feels quite natural.  Issue closed! Although you might want to put a note in the main page Readme about this... :)
