### ISSUE TITLE
Clue numbers very hard to read

### ISSUE THREAD

**Issue by Snowflake6** [sandsmark/recrossable#8]
The numbers in each cell corner are very faint compared to the light background.  Once filled in, they are white-on-black and a lot easier to read.  If they could be black-on-white instead of grey-on-white initially it would make it a lot easier to use in a less brightly lit room.

**Comment by PeterGrace** [comment]
I can confirm on a reMarkable2 the numbers in the cells are very light and tough to read.

**Comment by sandsmark** [comment]
I assume this fixes it?: https://github.com/sandsmark/recrossable/pull/11

**Comment by PeterGrace** [comment]
Yep, I believe @Snowflake6 is actually running the binary from my CI build currently.

**Comment by Snowflake6** [comment]
I am.  The situation is much improved, thanks!  I may have made the text even darker, but this is at least readable now.

**Comment by Snowflake6** [comment]
Drat... I just did a round of updates on the rM and it looks like recrossable went from 0.0.2 to 0.0.3... And overwrote my corrected version.  @PeterGrace can we get yours rolled into the main branch?

**Comment by Snowflake6** [comment]
It looks like the new version has rolled out so i'll mark this as closed... The numbers are now much better.
